### ISSUE TITLE
[Question] Release an alpha/beta version of the package on npm registry.

### ISSUE THREAD

**Issue by ghoullier** [didavid61202/type-level-regexp#1]
Hello!

Thanks for your project.

Do you have any plan to release an early version of this package on npm registry?

**Comment by didavid61202** [comment]
Hi @ghoullier,
Just release [version 0.1.0](https://www.npmjs.com/package/type-level-regexp) on npm 🚀 , and updated the docs for Usages and simple to more complex examples.

Please give it a spin if you are interested, feedbacks and pr are welcome.😊
